update RBAC assertions
openshift-pipelines/release-tests pull request #38
Opened 2021-05-05 09:26 UTC by praveen4g0

* `RBAC` assertions update.
* Exposed event listeners routes cleanup upon test completion.

2021-05-05 11:46 UTC, praveen4g0 commented
/assign @savitaashture @ppitonak

2021-05-05 14:10 UTC, vdemeester approved these changes

2021-05-06 12:32 UTC, ppitonak requested changes
Something is still wrong with olm.spec. I tried installation
`CATALOG_SOURCE=redhat-operators CHANNEL=stable gauge run --env "default, test" --tags "install" --log-level=debug --verbose   specs/olm.spec` and it never finished...

```
2021/05/06 14:16:45 output: subscription.operators.coreos.com/openshift-pipelines-operator-rh created
      * Subscribe to operator    ...[PASS]
      * Wait for TektonConfig CR availability    ...[PASS]
2021/05/06 14:17:27 Waiting for availability of pipelines cr [pipeline]
      * Validate pipelines deployment    ...[PASS]
2021/05/06 14:17:48 Waiting for availability of triggers cr [trigger]
2021/05/06 14:17:53 Waiting for availability of triggers cr [trigger]
2021/05/06 14:17:58 Waiting for availability of triggers cr [trigger]
      * Validate triggers deployment     ...[PASS]
2021/05/06 14:18:18 Waiting for availability of addon cr
      * Verify TektonAddons Install status       ...[PASS]
```

2021-05-06 12:32 UTC, ppitonak commented on README.md
Let's change CHANNEL on line 156 to `stable`. The same applies to file `env/test/test.properties`

2021-05-07 14:56 UTC, ppitonak approved these changes
Actually this code runs fine so I'll merge it and update the channel in new PR.

2021-05-07 14:56 UTC, merged