Adding more steps to operator installation test case
openshift-pipelines/release-tests pull request #95
Opened 2022-11-15 05:16 UTC by VeereshAradhya

- Adding a step to verify the status of the tektoninstallersets
- Adding a step to verify if the default tektoninstallersets are present

2022-11-15 08:27 UTC, ppitonak requested changes

2022-11-15 08:27 UTC, ppitonak commented on specs/olm.spec
> +  * Validate tektoninstallersets
I would rename it to `Validate tektoninstallersets state` so that it's clear why we have two separate steps

2022-11-15 09:07 UTC, VeereshAradhya commented on pkg/k8s/k8s.go
> +			failedInstallersets = append(failedInstallersets, is.Name)
Reason meaning, why the installerset is in failed state?

2022-11-16 12:24 UTC, ppitonak commented on pkg/k8s/k8s.go
> +			failedInstallersets = append(failedInstallersets, is.Name)
yes, whatever appears in reason column
```
$ oc get tektoninstallerset
NAME                                     READY   REASON
addon-clustertasks-t6tlz                 True
```

2022-11-18 05:38 UTC, VeereshAradhya commented on pkg/k8s/k8s.go
> +			failedInstallersets = append(failedInstallersets, is.Name)
I want to use API here instead of cli. Is it ok if I add this in the next PR?

2022-11-18 05:39 UTC, VeereshAradhya commented on pkg/k8s/k8s.go
> +			failedInstallersets = append(failedInstallersets, is.Name)
I am trying to get installerset to `Error` state to test this, but I am unable to do it

2022-11-22 12:48 UTC, ppitonak commented on pkg/k8s/k8s.go
> +			failedInstallersets = append(failedInstallersets, is.Name)
Sure, let's do it in new PR.

2022-11-22 12:48 UTC, ppitonak approved these changes

2022-11-24 07:51 UTC, merged